//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialNetwork.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немного о.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт заблокирован.
        /// </summary>
        public static string AccountIsBlocked {
            get {
                return ResourceManager.GetString("AccountIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр профиля.
        /// </summary>
        public static string AccountView {
            get {
                return ResourceManager.GetString("AccountView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить видео.
        /// </summary>
        public static string AddVideo {
            get {
                return ResourceManager.GetString("AddVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панель управления администратора.
        /// </summary>
        public static string AdminControlPanel {
            get {
                return ResourceManager.GetString("AdminControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string AdminRole {
            get {
                return ResourceManager.GetString("AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все поля обязательны к заполнению.
        /// </summary>
        public static string AllFieldsAreRequired {
            get {
                return ResourceManager.GetString("AllFieldsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсовой проект.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытк..
        /// </summary>
        public static string Attempt {
            get {
                return ResourceManager.GetString("Attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ось Х.
        /// </summary>
        public static string AxisXName {
            get {
                return ResourceManager.GetString("AxisXName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оcь Y.
        /// </summary>
        public static string AxisYName {
            get {
                return ResourceManager.GetString("AxisYName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основная информация.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокировать.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокировано.
        /// </summary>
        public static string BlockedTask {
            get {
                return ResourceManager.GetString("BlockedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        public static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по комментариям.
        /// </summary>
        public static string byComments {
            get {
                return ResourceManager.GetString("byComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по решениям.
        /// </summary>
        public static string bySolutions {
            get {
                return ResourceManager.GetString("bySolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название графика.
        /// </summary>
        public static string ChartName {
            get {
                return ResourceManager.GetString("ChartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to График.
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить решение.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментировать.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string CommentContent {
            get {
                return ResourceManager.GetString("CommentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить изменения.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите вашу учетную запись.
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правовая информация.
        /// </summary>
        public static string CopyrightInformation {
            get {
                return ResourceManager.GetString("CopyrightInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата добавления.
        /// </summary>
        public static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to детали.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        /// </summary>
        public static string ErrorHasOccurred {
            get {
                return ResourceManager.GetString("ErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при обработке вашего запроса..
        /// </summary>
        public static string ErrorWhileProcessing {
            get {
                return ResourceManager.GetString("ErrorWhileProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выражение.
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to например: sin(x).
        /// </summary>
        public static string ExpressionExample {
            get {
                return ResourceManager.GetString("ExpressionExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешний логин был удален.
        /// </summary>
        public static string ExternalLoginWasRemoved {
            get {
                return ResourceManager.GetString("ExternalLoginWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтры.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить тему.
        /// </summary>
        public static string FooterThemeChooser {
            get {
                return ResourceManager.GetString("FooterThemeChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumen (темная).
        /// </summary>
        public static string FooterThemeDark {
            get {
                return ResourceManager.GetString("FooterThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatti (светлая).
        /// </summary>
        public static string FooterThemeLight {
            get {
                return ResourceManager.GetString("FooterThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображения и видео.
        /// </summary>
        public static string ImagesAndVideos {
            get {
                return ResourceManager.GetString("ImagesAndVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Важно.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильно введено имя или пароль.
        /// </summary>
        public static string InvalidNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мне нравится.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопируйте ссылку в поле содержимого задачи.
        /// </summary>
        public static string LinkInfo {
            get {
                return ResourceManager.GetString("LinkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец блокировки.
        /// </summary>
        public static string LockoutEndDate {
            get {
                return ResourceManager.GetString("LockoutEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщить об ошибке.
        /// </summary>
        public static string MessageMistake {
            get {
                return ResourceManager.GetString("MessageMistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string NavBarLogin {
            get {
                return ResourceManager.GetString("NavBarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string NavBarLogoff {
            get {
                return ResourceManager.GetString("NavBarLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string NavBarRegister {
            get {
                return ResourceManager.GetString("NavBarRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый поиск.
        /// </summary>
        public static string NewSearch {
            get {
                return ResourceManager.GetString("NewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь еще не существует или не подтвержден.
        /// </summary>
        public static string NotExistOrNotConfirmed {
            get {
                return ResourceManager.GetString("NotExistOrNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не найдено.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        public static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был изменен.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был установлен.
        /// </summary>
        public static string PasswordSet {
            get {
                return ResourceManager.GetString("PasswordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по популярности.
        /// </summary>
        public static string popular {
            get {
                return ResourceManager.GetString("popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль успешно обновлен.
        /// </summary>
        public static string ProfileHasBeenUpdated {
            get {
                return ResourceManager.GetString("ProfileHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложите решение.
        /// </summary>
        public static string ProposeSolution {
            get {
                return ResourceManager.GetString("ProposeSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложить задачу.
        /// </summary>
        public static string ProposeTask {
            get {
                return ResourceManager.GetString("ProposeTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложите вашу задачу.
        /// </summary>
        public static string ProposeYourTask {
            get {
                return ResourceManager.GetString("ProposeYourTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по дате.
        /// </summary>
        public static string recent {
            get {
                return ResourceManager.GetString("recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательно к заполнению.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс.
        /// </summary>
        public static string ResetFilters {
            get {
                return ResourceManager.GetString("ResetFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат поиска.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страницы.
        /// </summary>
        public static string SearchResultPages {
            get {
                return ResourceManager.GetString("SearchResultPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string SearchResultUsers {
            get {
                return ResourceManager.GetString("SearchResultUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решение.
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решения.
        /// </summary>
        public static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шаг.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Облако тегов.
        /// </summary>
        public static string TagCloud {
            get {
                return ResourceManager.GetString("TagCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теги.
        /// </summary>
        public static string TagsName {
            get {
                return ResourceManager.GetString("TagsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, используйте поиск перед отправкой задачи, чтобы убедиться что ваша здача не повторяется. Оставляя публикацию, вы подтверждаете, что содержимое соблюдает.
        /// </summary>
        public static string TaskLegalInfo1 {
            get {
                return ResourceManager.GetString("TaskLegalInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to и не нарушает права других пользователей. Если вы сомневаетесь, посетите сраницу.
        /// </summary>
        public static string TaskLegalInfo2 {
            get {
                return ResourceManager.GetString("TaskLegalInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to перед публикацией..
        /// </summary>
        public static string TaskLegalInfo3 {
            get {
                return ResourceManager.GetString("TaskLegalInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия использования.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить изображение.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытки решений.
        /// </summary>
        public static string UserAttemptAmount {
            get {
                return ResourceManager.GetString("UserAttemptAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить пароль.
        /// </summary>
        public static string UserChangePassword {
            get {
                return ResourceManager.GetString("UserChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить данные профиля.
        /// </summary>
        public static string UserEditAccountInfo {
            get {
                return ResourceManager.GetString("UserEditAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле должно быть заполнено.
        /// </summary>
        public static string UserEditAccountUserNameError {
            get {
                return ResourceManager.GetString("UserEditAccountUserNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы еще не решили ни одной задачи.
        /// </summary>
        public static string UserEmplySolutionList {
            get {
                return ResourceManager.GetString("UserEmplySolutionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не опубликовали ни одной задачи.
        /// </summary>
        public static string UserEmptyTaskList {
            get {
                return ResourceManager.GetString("UserEmptyTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решения.
        /// </summary>
        public static string UserMySolutions {
            get {
                return ResourceManager.GetString("UserMySolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи.
        /// </summary>
        public static string UserMyTasks {
            get {
                return ResourceManager.GetString("UserMyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя должно содержать от 3 до 30 символов.
        /// </summary>
        public static string UserNameLenghtError {
            get {
                return ResourceManager.GetString("UserNameLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        public static string UserRate {
            get {
                return ResourceManager.GetString("UserRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решенные задачи.
        /// </summary>
        public static string UserSolutionAmount {
            get {
                return ResourceManager.GetString("UserSolutionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложенные задачи.
        /// </summary>
        public static string UserTaskAmount {
            get {
                return ResourceManager.GetString("UserTaskAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условие.
        /// </summary>
        public static string UserTaskContent {
            get {
                return ResourceManager.GetString("UserTaskContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string UserTaskStatus {
            get {
                return ResourceManager.GetString("UserTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string UserTaskTitle {
            get {
                return ResourceManager.GetString("UserTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to читать далее.
        /// </summary>
        public static string viewMore {
            get {
                return ResourceManager.GetString("viewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to профиль.
        /// </summary>
        public static string viewProfile {
            get {
                return ResourceManager.GetString("viewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите комментарий.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете решить заблокированную задачу.
        /// </summary>
        public static string YouCantSolveBlockTask {
            get {
                return ResourceManager.GetString("YouCantSolveBlockTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это же ваша задача!.
        /// </summary>
        public static string YourOwnTask {
            get {
                return ResourceManager.GetString("YourOwnTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже решили эту задачу.
        /// </summary>
        public static string YouSolvedSolution {
            get {
                return ResourceManager.GetString("YouSolvedSolution", resourceCulture);
            }
        }
    }
}
